version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - network
volumes:
  docker-nest-postgres:
networks:
    network:
     driver: bridge