version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./server/:/usr/src/app
    env_file:
      - ./server/prisma.env
    command: npm run start:dev
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  docker-nest-postgres:
