version: '3.8'
services:
  server:
    depends_on:
      - db
    build:
      context: server
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/src
  db:
    image: postgres:15
    restart: always
    expose:
      - '5432'
    env_file:
      - ./server/.env